export let state = {
  config: null,
  scores: {},
  mode: 'judge',
  orgUnlocked: false,
  orgTab: 'setup',
  eventId: null,
  judge: null,
  judgeUnlocked: false,
  categoryId: null,
  contestantId: null,
  draft: {},
  expandedCats: {},
  categoryFilter: '',
  contestantFilters: {},
  orgEditKey: null,
  orgEditDraft: {},
  expandedCompetitionSettings: false,
  tallyStageFilter: '',
  organizerEditSummary: {},
  scoreHistoryCache: {},
  historyPanelCategoryId: null,
  adminUnlocked: false,
  adminToken: null,
  adminClients: null,
  adminEvents: null,
};
